# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  # Default build command.
  command = "npm run build"
  
[[redirects]]
  from = "/*"
  to = "/"
  status = 200